//! Common node parameter values (lifetime, spawn rate, bind types, etc.).

use super::enums::{BindType, GenerationTiming, RemovalTiming, TranslationParentBindType};
use super::primitives::{RandomFloat, RandomInt, RefMinMax, TriggerValues};

/// Common parameters for all node types (lifetime, generation, binding).
///
/// This is the unified runtime struct produced from 4 different binary layouts
/// depending on version.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ParameterCommonValues {
    /// Dynamic equation reference for max_generation (-1 = none).
    pub ref_eq_max_generation: i32,
    /// Dynamic equation references for life.
    pub ref_eq_life: RefMinMax,
    /// Maximum number of particles generated by this node.
    pub max_generation: i32,
    /// How translation is bound to parent.
    pub translation_bind_type: TranslationParentBindType,
    /// How rotation is bound to parent.
    pub rotation_bind_type: BindType,
    /// How scaling is bound to parent.
    pub scaling_bind_type: BindType,
    /// Particle lifetime range.
    pub life: RandomInt,
    /// Generation (spawn timing) parameters.
    pub generation: GenerationParameter,
    /// Removal parameters.
    pub removal: RemovalParameter,
}

/// Generation (spawn timing) parameters.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GenerationParameter {
    /// Dynamic equation references for interval.
    pub ref_eq_interval: RefMinMax,
    /// Dynamic equation references for offset.
    pub ref_eq_offset: RefMinMax,
    /// Dynamic equation references for burst count.
    pub ref_eq_burst: RefMinMax,
    /// Generation timing type (Continuous or Trigger).
    pub type_: GenerationTiming,
    /// Time interval between particle spawns.
    pub interval: RandomFloat,
    /// Time offset before first spawn.
    pub offset: RandomFloat,
    /// Number of particles per burst.
    pub burst: RandomInt,
    /// Trigger to start generation.
    pub trigger_to_start: TriggerValues,
    /// Trigger to stop generation.
    pub trigger_to_stop: TriggerValues,
    /// Trigger to begin generating.
    pub trigger_to_generate: TriggerValues,
}

/// Removal (particle death) parameters.
#[derive(Debug, Clone)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct RemovalParameter {
    /// Bitflags indicating removal conditions.
    pub flags: RemovalTiming,
    /// Trigger for removal.
    pub trigger_to_remove: TriggerValues,
}
